trigger:
  branches:
    include:
      - 'main'
  paths:
    exclude:
      - 'README.md'
      - 'azure_pipelines.yml'
      - 'templates/*'
pr: none

pool: 
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - template: templates/build.yml
          
  - stage: Deploy
    dependsOn: Build
    jobs:
      - template: templates/deploy.yml
