pool: 
  name: Default

resources:
  webhooks:
    - webhook: WebHook
      connection: CDWebHook_Connection

steps:
  - script: echo "Commit URL => ${{ parameters.WebHook.repository.commits.url }}"
  
