trigger:
  branches:
    include:
      - 'main'
  paths:
    exclude:
      - 'README.md'
      - 'azure_pipelines.yml'
      - 'templates/*'
pr: none

pool: 
  vmImage: ubuntu-latest

parameters:
  - name: Lambda_Function_Name
    displayName: 'Lambda Function Name'
    type: string
    default: ServerlessCalculator

stages:
  - stage: Build
    jobs:
      - template: templates/build.yml
          
  - stage: Deploy
    dependsOn: Build
    jobs:
      - template: templates/deploy.yml
        parameters:
          Lambda_Function_Name: ${{ parameters.Lambda_Function_Name }}
