trigger:
  - main
  
pool: 
  name: Default

resources:
  webhooks:
    - webhook: WebHook
      connection: CDWebHook_Connection

steps:
  - script: echo ${{ parameters.WebHook.resource.repository.full_name }}
