trigger: none
pr: none

pool: 
  vmImage: ubuntu-latest

resources:
  webhooks:
    - webhook: WebHook
      connection: CDWebHook_Connection
      trigger:
        branches:
        - main
        - azure-pipelines

steps: 
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.x'
      
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: '$(System.DefaultWorkingDirectory)/app'
      customCommand: 'install'
  
  - task: trivy@1
    inputs:
      version: 'latest'
      path: '$(System.DefaultWorkingDirectory)'
      exitCode: '0'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/app'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: LambdaDeployFunction@1
    inputs:
      awsCredentials: 'AWS_Connection'
      regionName: 'us-east-1'
      deploymentMode: 'codeonly'
      functionName: 'hello_world'
      codeLocation: 'localfile'
      localZipFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      