trigger:
  branches:
    include:
      - 'main'
      - 'azure-pipelines'
pr: none

pool: 
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Prerequisites
        displayName: 'Prerequisites'
        steps:
          - task: NodeTool@0
            inputs:
              versionSource: 'spec'
              versionSpec: '20.x'
      - job: BuildArtifact
        displayName: 'Build Artifact'
        dependsOn: Prerequisites
        condition: succeeded()
        steps:
          - task: Npm@1
            inputs:
              command: 'custom'
              workingDir: '$(System.DefaultWorkingDirectory)/app'
              customCommand: 'install'
          - task: trivy@1
            inputs:
              version: 'latest'
              path: '.'
              exitCode: '0'
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/app'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            inputs:
              PathToPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(Build.BuildId).zip'
              publishLocation: 'Container'
          
  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: DownloadArtifact
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: '$(Build.BuildId).zip'
              targetPath: '$(Build.ArtifactStagingDirectory)'
      - job: DeployArtifact
        dependsOn: DownloadArtifact
        condition: succeeded()
        steps:
          - task: LambdaDeployFunction@1
            inputs:
              awsCredentials: 'AWS_Connection'
              regionName: 'us-east-1'
              deploymentMode: 'codeonly'
              functionName: 'hello_world'
              codeLocation: 'localfile'
              localZipFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
