trigger:
  - main
  
pool: 
  vmImage: ubuntu-latest

resources:
  webhooks:
    - webhook: WebHook
      connection: CDWebHook_Connection

steps:  
- script: echo ${{ parameters.WebHook.resource.repository.full_name }}
