trigger:
  branches:
    include:
      - 'main'
      - 'azure-pipelines'
pr: none

pool: 
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSource: 'spec'
              versionSpec: '20.x'
          - task: Npm@1
            inputs:
              command: 'custom'
              workingDir: '$(System.DefaultWorkingDirectory)/app'
              customCommand: 'install'
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/app'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

  - stage: Scanning
    dependsOn: Build
    jobs:
      - job: Security_Scanning
        steps:
          - task: trivy@1
            inputs:
              version: 'latest'
              path: '.'
              exitCode: '0'

  - stage: Deploy
    dependsOn: Scanning
    jobs:
      - job: Deploy
        steps:
          - task: LambdaDeployFunction@1
            inputs:
              awsCredentials: 'AWS_Connection'
              regionName: 'us-east-1'
              deploymentMode: 'codeonly'
              functionName: 'hello_world'
              codeLocation: 'localfile'
              localZipFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
