jobs:
    - job: BuildArtifact
      displayName: 'Build Artifact'
      condition: succeeded()
      steps:
        - task: Npm@1
          displayName: 'Dependencies installation'
          inputs:
            command: 'custom'
            workingDir: '$(System.DefaultWorkingDirectory)/app'
            customCommand: 'install'
        - template: sca_scanner.yml
        - task: ArchiveFiles@2
          displayName: 'Artifact archiving'
          inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/app'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
        - task: PublishPipelineArtifact@1
          displayName: 'Artifact publishing'
          inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: '$(Build.BuildId).zip'
