parameters:
  - name: Lambda_Function_Name
    type: string

jobs:
  - job: DeployArtifact
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Artifact download'
      inputs:
          artifact: '$(Build.BuildId).zip'
    - task: LambdaDeployFunction@1
      displayName: 'Lambda function deploy'
      inputs:
          awsCredentials: 'AWS_Connection'
          regionName: 'us-east-1'
          deploymentMode: 'codeonly'
          functionName: ${{ parameters.Lambda_Function_Name }}
          codeLocation: 'localfile'
          localZipFile: '$(Pipeline.Workspace)/$(Build.BuildId).zip'
          